### ISSUE TITLE
hashKey is only used for table creation, fails for reads/writes

### ISSUE THREAD

**Issue by lemieuxster** [ca98am79/connect-dynamodb#35]
```
            Key: {
                id: {
                    'S': sid
                }
            }
```

Uses `id` as a hard-coded value. Should use value of `hashKey` option. 

```
var KeyValue = {}
KeyValue[this.hashKey] = { 'S' : sid };

...

Key : KeyValue

```

Results in ValidationException

**Comment by ollyfg** [comment]
A bit old now, but I just came across this exact problem, and have written up a quick PR: [#53](https://github.com/ca98am79/connect-dynamodb/pull/53).
