### ISSUE TITLE
Support for DynamoDB TTL 

### ISSUE THREAD

**Issue by neverendingqs** [ca98am79/connect-dynamodb#39]
With the advent of [DynamoDB TTL](https://aws.amazon.com/about-aws/whats-new/2017/02/amazon-dynamodb-now-supports-automatic-item-expiration-with-time-to-live-ttl/), it is now possible to automatically delete rows (sessions) from DynamoDB automatically based on a field (e.g. `expires`). Unfortunately, it only currently supports seconds since epoch (not milliseconds, which is what is stored in `expires`).

Is there a way to leverage this new DynamoDB feature?

Related: https://forums.aws.amazon.com/thread.jspa?threadID=251306, as it could also be a feature request on AWS's end.

**Comment by ca98am79** [comment]
thanks - for now I think adding an `expires_at` attribute for this may be best.  It is probably also best to default to using DynamoDB TTL, and setting `reapInterval` to 0 (no reaping) by default as a legacy setting.

**Comment by smaclell** [comment]
I think I might try making a PR to add this functionality. We need it for a project at work and I think I can get some time to work on it.

How would you want to handle migrating existing users? Leave their data/table and treat it as a breaking change? Anything I should know prior to contributing? Thanks for the solid project.

**Comment by uvforce** [comment]
@ca98am79 I am a newbie, and wonder how to add expires_at attribute, or dfault to using DynamDB TTL

**Comment by ca98am79** [comment]
implemented with #43
