### ISSUE TITLE
Is there a way to use this to connect to an existing table in an existing stack?

### ISSUE THREAD

**Issue by StJohn3D** [ca98am79/connect-dynamodb#47]
Hi, I'd rather not create a new session table every time I Deploy. I have a large cloud formation yaml file that spins up all the AWS resources I need in my stack. I was hoping to use this package to connect to the existing table. But the documentation looks like it only creates tables.

Is there a way to use this package to connect to my existing table?

**Comment by ca98am79** [comment]
yes you don't have to create a table every time, you can include the `table` in the config options

**Comment by StJohn3D** [comment]
Must be a permissions thing then because I _did_ try that.
