### ISSUE TITLE
Support passing express-session directly as a param in init

### ISSUE THREAD

**Issue by therealsanmah** [ca98am79/connect-dynamodb#54]
Allow the flexibility to pass the express-session directly as a parameter to the adapter constructor. 

Today, then way connect-dynamodb seems to allow initialization is like this:
```
var session = require('express-session');
var DynamoDBStore = require('connect-dynamodb')({session: session});
```

Where as frameworks such as sails, initialize the store like [this](https://github.com/balderdashy/sails/blob/d5775cdb68fe12680e87652c23bf300c75417b15/lib/hooks/session/index.js#L405). Consequently, connect-dynamodb is not directly compatible with sails, which is gaining popularity quickly.

The issue is to request support initialisation by passing the express-session directly as a param. Like this:
```
var DynamoDBStore = require('connect-dynamodb')(require('express-session'));
```

This is today also supported by [connect-mongo](https://github.com/jdesboeufs/connect-mongo) and will bring us feature-parity.

**Comment by ca98am79** [comment]
thanks!
