### ISSUE TITLE
OnDemand Table

### ISSUE THREAD

**Issue by natac13** [ca98am79/connect-dynamodb#62]
Is it possible to create an ondemand Table instead of a provisioned one.

I looked over your [code](https://github.com/ca98am79/connect-dynamodb/blob/bdf9fcd1c9070cc17b160122f38735aea8ec3a86/lib/connect-dynamodb.js#L73-L87) and did not seem to think this was possible?
Is there a reason why?

Thanks so much for the package.

**Comment by sidwarkd** [comment]
+1 on using an existing On-Demand table.

**Comment by sidwarkd** [comment]
@natac13 I just found that if you create the On-Demand table and just specify the `table` option it will use it. So while the library only creates provisioned tables you can still point it to an existing On-Demand table. Hope that helps.

**Comment by ca98am79** [comment]
yes, thanks - the `table` option should work for this
