### ISSUE TITLE
Disable checking if sessions table exists

### ISSUE THREAD

**Issue by laszlo-dev-13** [ca98am79/connect-dynamodb#67]
Is there a way to disable always checking if the table exists?
The reason for this is that we plan to use express-session with dynamoDb and serverless (using aws lambda), so checking if the table exists each time a lambda function gets fired up seems redundant.

**Comment by lancegliser** [comment]
I'm actually doing the same thing on AWS. It's a cost to run the table check, to be sure. A simple table describe is fairly cheap though. 

In the future, if this feature is produced we'll have to adjust for #76 . I expect we could take in `initialized?: boolean` in the options post refactor.
