### ISSUE TITLE
Feature Request: Can the connect dependency be removed from package.json?

### ISSUE THREAD

**Issue by tfrancois** [ca98am79/connect-dynamodb#97]
I just realized that the `connect` package is included as a dependency and is not referenced anywhere in the code.  To keep this package lean for portability, can we remove this unnecessary dependency - or at least move it to devDependencies instead?

Thank you!

**Comment by tfrancois** [comment]
@yutak23  Is there any plans to merge this pull request anytime soon - I really would rather use this package rather than the fork?  Please advise - and if so, can we also respectfully patch/resolve new issue #99 while we're at it as well please?

**Comment by yutak23** [comment]
> @yutak23 Is there any plans to merge this pull request anytime soon - I really would rather use this package rather than the fork? Please advise - and if so, can we also respectfully patch/resolve new issue #99 while we're at it as well please?

@tfrancois ,
I am not the owner or maintainer of this project, so I can't do the merge, but I can send a PR, so I will try to resolve this issue as well!

**Comment by tfrancois** [comment]
@ca98am79 Thank you for responding to this so quickly.
@yutak23 Any luck on resolving #99 - with these two issues resolved I'd be happy releasing my projects that rely on this library to production.  
Thank you both!
