### ISSUE TITLE
Bug: Error when using specialKeys option with Number field

### ISSUE THREAD

**Issue by tfrancois** [ca98am79/connect-dynamodb#99]
Hi, I noticed that when I reference a numeric/integer field in the sess object that I would like to appear in the root level of the record item using the specialKeys option it generates the following error:

```
specialKeys: [
  { name: 'authenticated', type: 'BOOL' },
  { name: 'eventUTC', type: 'N' }
]
```

> NUMBER_VALUE cannot be converted to String

FYI - the `eventUTC` property holds a Unix timestamp / epoch integer in the session (before workaround conversion to string).

The workaround is to set the value in the session object to a string and no error occurs and the property is written out to the record item as a number attribute correctly.  Can this issue be resolved so that I can preserve the correct data type in the session object (numeric) as well?  Thank you!

**Comment by yutak23** [comment]
I wrote a test and tried to reproduce the bug, but could not reproduce it.

https://github.com/yutak23/connect-dynamodb/blob/feature/test-add-specialkey/test/test.js#L197

```
$ npm run test

> connect-dynamodb@3.0.4 test
> mocha --timeout 5000



  ConnectDynamoDB
    Constructor
      ✔ should take session as argument
      ✔ should take session as one of the options

  DynamoDBStore
    Instantiation
      ✔ should be able to be created
      ✔ should accept a client as an option
    Initializing
      creating a table
        ✔ Should create the table if it doesn't exist and skip subsequent calls (199ms)
      using an existing table
        ✔ should not call the create table function (51ms)
      skip initializing
        ✔ Should skip table existence checks and creation
    Setting
      ✔ should store data correctly (120ms)
      ✔ should store data correctly with specialKeys option (180ms)
    Getting
      ✔ should get data correctly (51ms)
      ✔ does not crash on invalid session object
    Touching
      ✔ should touch data correctly (1543ms)
    Destroying
      ✔ should destroy data correctly (123ms)
    Reaping
      ✔ should reap data correctly (234ms)


  14 passing (3s)
```

**Comment by tfrancois** [comment]
I double and triple-checked it is definitely an issue - I am using AWS v3 client-dynamodb and I've tried both the native client and the marshalled docClient.  Either way the fix would be as follows:

![image](https://github.com/user-attachments/assets/90468485-1d4e-4903-86d3-032f623c1e3d)

Changing line 231 to fixes the issue:
`item[key.type] = (key.type == 'N') ? JSON.stringify(sess[key.name]) : sess[key.name];`

Notice how `expires` on line 216 preemptively avoidsthis issue.

May I respectfully propose this as the fix?  Not familiar with how to submit a PR and see no need to create a fork for 1 line of code.

Please help!

**Comment by tfrancois** [comment]
Thank you very much gentlemen!
